cart/urls.py
from django.urls import path
from .views import cart_add, cart_detail, cart, cart_update, cart_clear, cart_remove


urlpatterns = [
    path("", cart_add, name="cart-add"),
    path("<int:productid>/", cart_detail, name="cart-detail"),
    path("total", cart, name="cart"),
    path("update", cart_update, name="cart-update"),
    path("delete", cart_clear, name="delete"),
    path("remove", cart_remove, name="remove"),
]

shop/urls.py
from django.urls import path
from .views import index, login_view, logout_view

app_name = 'shop'

urlpatterns = [
    path("", index, name="home"),
    path("login", login_view, name="login"),
    path("logout", logout_view, name="logout"),
]

shop_watch/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('shop.urls')),
    path("cart/", include('cart.urls')),
    path("order/", include('order.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <title>Title</title>
  <!-- Required meta tags -->
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css"
    integrity="sha512-1sCRPdkRXhBV2PBLUdRb4tMg1w2YPf37qatUFeS7zlBy7jJI8Lf4VHwWfZZfpXtYSLy85pkm9GaYVYMfw5BC1A=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous" />
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/cart.css' %}">
  <style>
    body{
      background: linear-gradient(141deg, #0fb8ad 0%, #1fc8db 51%, #2cb5e8 75%);
    }
  </style>
  
  <script>
    function getCookie(name) {
      let cookieValue=null;

      if (document.cookie && document.cookie !=='') {
        const cookies=document.cookie.split(';');

        for (let i=0; i < cookies.length; i++) {
          const cookie=cookies[i].trim();

          // Does this cookie string begin with the name we want?
          if (cookie.substring(0, name.length + 1)===(name + '=')) {
            cookieValue=decodeURIComponent(cookie.substring(name.length + 1));
            break;
          }
        }
      }

      return cookieValue;
    }

    const csrftoken=getCookie('csrftoken');
  </script>
    
    
 
</head>

<body>
  <div>
    {% include 'navbar.html' %}

    <div class="container mt-2">
      {% block message %}
  
      {% endblock message %}
    </div>
  
  
    {% block content %} {% endblock content %}
  </div>
  

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>
  {% block js %}

  {% endblock js %}
</body>

</html>

templates/navbar.html
<nav class="navbar navbar-expand-sm navbar-dark bg-dark p-0 ">
  <div class="container">
    <a href="/" class="navbar-brand">Watch</a>
    <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav">
        <li class="nav-item px-2">
          <a href="/" class="nav-link active">Dashboard</a>
        </li>

      </ul>

      <ul class="navbar-nav ml-auto ul-login-logout">
        {% if request.user.is_authenticated %}
        <li class="nav-item dropdown mr-3">
          <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">
            <i class="fas fa-user"></i> Wellcome
          </a>
          <div class="dropdown-menu">
            <a href="profile.html" class="dropdown-item">
              <i class="fas fa-user-circle"></i> Profile
            </a>
            <a href="settings.html" class="dropdown-item">
              <i class="fas fa-cog"></i> Settings
            </a>
          </div>
        </li>

        <li class="nav-item">
          <a href='{% url "shop:logout" %}?next={{request.path}}' class="nav-link">
            <i class="fa-solid fa-user"></i> Logout
          </a>
        </li>
        {% else %}
        <li class="nav-item">
          <a href="#" class="nav-link modalLogin" data-toggle="modal" data-target="#addLoginModal">
            <i class="fas fa-user-times"></i> Login
          </a>
        </li>
        {% endif %}


        <li class="nav-item">

          <a href='{% url "cart" %}' class="nav-link">
            <i class="fa-solid fa-cart-shopping"></i> <span class="badge badge-light">{{ cart|length }}</span>
          </a>
        </li>
      </ul>
    </div>
  </div>
</nav>



<!-- ADD POST MODAL -->
<div class="modal fade loginModal" id="addLoginModal">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header bg-primary text-white">
        <h5 class="modal-title">Login</h5>
        <button class="close" data-dismiss="modal">
          <span>&times;</span>
        </button>
      </div>
      <div class="modal-body">
        {% comment %} alert {% endcomment %}



        <form method='POST'>
          {% csrf_token %}
          <div class="form-group">
            <label for="title">User</label>
            <input type="text" class="form-control username" name='username' required>
            <div class="invalid-feedback">
              Username không được để trống
            </div>
          </div>
          <div class="form-group">
            <label for="title">Password</label>
            <input type="password" class="form-control password" name='password' required>
            <div class="invalid-feedback">
              Password không được để trống
            </div>
          </div>

          <a href="{% url 'shop:login' %}?next={{request.path}}" class="btn btn-outline-primary btn-block btn-login">Login</a>
         
        </form>
      </div>

    </div>
  </div>
</div>